<img src="uc3m-logo.jpg" alt="UC3M logo" width="200"/>

# First Homework: Linear and Discrete Models (Topics 2, 3)
## BsC in Data Science and Engineering - Optimization and Analytics (2022-2023)

Author: Rodrigo Oliver Coimbra (NIA: 100451788)

In [1]:
import numpy as np

class Activity:
    def __init__(self, name, start, end, normal_time, crash_time, normal_cost, crash_cost):
        self.name = name
        self.start = start
        self.end = end
        self.normal_time = normal_time
        self.crash_time = crash_time
        self.normal_cost = normal_cost
        self.crash_cost = crash_cost
        
        if normal_cost == 0 or crash_time == 0:
            self.C = 0
        else:
            self.C = int((crash_cost - normal_cost)/(normal_time - crash_time))

def crange(char1, char2):
    for char in range(ord(char1), ord(char2)):
        yield chr(char)
        
# Incidence matrix (automatic form)
def generateA (A,start_nodes,end_nodes):
    count = 0
    for i in zip(start_nodes,end_nodes):
        A[i[0]][count] = 1
        A[i[1]][count] = -1
        count+=1


In [2]:
activity_list = [Activity('A', 1, 2, 3, 2, 16_000, 18_000),
               Activity('B', 2, 3, 5, 3, 20_000, 23_000),
               Activity('C', 2, 4, 3, 2, 4_000, 8_000),
               Activity('D', 4, 5, 1, 0.5, 1_000, 1_500),
               Activity('E', 3, 7, 3, 1, 12_000, 17_000),
               Activity('F', 5, 6, 4, 2, 20_000, 26_000),
               Activity('G', 4, 6, 2, 1, 1_000, 1_800),
               Activity('H', 6, 7, 3, 1, 1_200, 2_600),
               Activity('I', 7, 8, 2, 1.5, 1_000, 1_400),
               Activity('Dummy', 3, 5, 0, 0, 0, 0)
                ]

E = 8
A = 10



start_nodes = [(a.start-1) for a in activity_list]
end_nodes = [(a.end-1) for a in activity_list]
M = np.zeros((E, len(end_nodes)))
generateA(M,start_nodes,end_nodes)

#print(start_nodes)
#print(end_nodes)
#print(M)

diff_time = [(a.normal_time - a.crash_time) for a in activity_list]
c = [a.C for a in activity_list]
#print([a.normal_time for a in activity_list])
normal_time = [a.normal_time for a in activity_list]
print(f"{normal_time=}")
#print(diff_time)
#print(c)

activity_dict = {}

activity_id = {}

for i, e in enumerate(activity_list):
   activity_id[i] = (e.start-1, e.end-1)

print(f"{activity_id=}\n") 

for i in range(E):
   for j in range(A):
      if M[i][j] == -1:
         activity_dict[(i,j)] = activity_id[j]

# With activity_dict we obtain the position
# in the incidence matrix of each one of the
# activities (arcs) in the format:
# (i,j) = (a,b) where i,j are the rows/cols
# of the incidence matrix
print(f"{activity_dict=}")

#print(len(activity_id))
#print(len(activity_dict))

"""
   01  12  13  34  26  45  35  56  67  24
[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.] # 0
 [-1.  1.  1.  0.  0.  0.  0.  0.  0.  0.] # 1
 [ 0. -1.  0.  0.  1.  0.  0.  0.  0.  1.] # 2
 [ 0.  0. -1.  1.  0.  0.  1.  0.  0.  0.] # 3
 [ 0.  0.  0. -1.  0.  1.  0.  0.  0. -1.] # 4
 [ 0.  0.  0.  0.  0. -1. -1.  1.  0.  0.] # 5
 [ 0.  0.  0.  0. -1.  0.  0. -1.  1.  0.] # 6
 [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0.] # 7
"""

normal_time=[3, 5, 3, 1, 3, 4, 2, 3, 2, 0]
activity_id={0: (0, 1), 1: (1, 2), 2: (1, 3), 3: (3, 4), 4: (2, 6), 5: (4, 5), 6: (3, 5), 7: (5, 6), 8: (6, 7), 9: (2, 4)}

activity_dict={(1, 0): (0, 1), (2, 1): (1, 2), (3, 2): (1, 3), (4, 3): (3, 4), (4, 9): (2, 4), (5, 5): (4, 5), (5, 6): (3, 5), (6, 4): (2, 6), (6, 7): (5, 6), (7, 8): (6, 7)}


'\n   01  12  13  34  26  45  35  56  67  24\n[[ 1.  0.  0.  0.  0.  0.  0.  0.  0.  0.] # 0\n [-1.  1.  1.  0.  0.  0.  0.  0.  0.  0.] # 1\n [ 0. -1.  0.  0.  1.  0.  0.  0.  0.  1.] # 2\n [ 0.  0. -1.  1.  0.  0.  1.  0.  0.  0.] # 3\n [ 0.  0.  0. -1.  0.  1.  0.  0.  0. -1.] # 4\n [ 0.  0.  0.  0.  0. -1. -1.  1.  0.  0.] # 5\n [ 0.  0.  0.  0. -1.  0.  0. -1.  1.  0.] # 6\n [ 0.  0.  0.  0.  0.  0.  0.  0. -1.  0.] # 7\n'

In [3]:
""""
for i, e in enumerate(M):
    mem = []
    for j, a in enumerate(e):
        if a == 1:
            if e not in mem:
                mem.append(e)
                print(f"x[{i+1}] + y[{j}] - x[{j}] >= {normal_time[j]}")
"""

"""
r = activity_dict.items()
for e in endpoint_list:
    if endpoint_list.count(e) != 1:
"""

res = activity_dict

"""
# WITHOUT DUPLICATES
temp = []
res = dict()
for key, val in activity_dict.items():
    if val[1] not in temp:
        temp.append(val[1])
        res[key] = val
        
print(f"{res=}")
print(f"{len(res)=}")
print(f"{len(activity_dict)=}")

for r in res.items():
    
    print(f"x{r[1][1]} >= n{r[1][0]}{r[1][1]} - y{r[1][0]}{r[1][1]} + x{r[1][0]}")
    print(f"x{r[1][1]} >= n{r[0][1]} - y{r[0][1]} + x{r[1][0]}")
    print()
    #print(r[0])
    #print(r[1])

"""
    
    
"""
# WITH DUPLICATES
for r in activity_dict.items():
    
    print(f"x{r[1][1]} >= n{r[1][0]}{r[1][1]} - y{r[1][0]}{r[1][1]} + x{r[1][0]}")
    #print(r[0])
    #print(r[1])
"""



'\n# WITH DUPLICATES\nfor r in activity_dict.items():\n    \n    print(f"x{r[1][1]} >= n{r[1][0]}{r[1][1]} - y{r[1][0]}{r[1][1]} + x{r[1][0]}")\n    #print(r[0])\n    #print(r[1])\n'

In [4]:
from pyomo.environ import *

model = ConcreteModel()

event_labels = [e for e in range(E)]
activity_labels = [a for a in range(A)]

model.i = Set(initialize = event_labels)
model.j = Set(initialize = activity_labels)

model.i.pprint()
model.j.pprint()

i : Size=1, Index=None, Ordered=Insertion
    Key  : Dimen : Domain : Size : Members
    None :     1 :    Any :    8 : {0, 1, 2, 3, 4, 5, 6, 7}
j : Size=1, Index=None, Ordered=Insertion
    Key  : Dimen : Domain : Size : Members
    None :     1 :    Any :   10 : {0, 1, 2, 3, 4, 5, 6, 7, 8, 9}


In [5]:
model.x = Var(model.i, within = NonNegativeReals)
model.y = Var(model.j, within = NonNegativeReals)

model.x.pprint()
model.y.pprint()

x : Size=8, Index=i
    Key : Lower : Value : Upper : Fixed : Stale : Domain
      0 :     0 :  None :  None : False :  True : NonNegativeReals
      1 :     0 :  None :  None : False :  True : NonNegativeReals
      2 :     0 :  None :  None : False :  True : NonNegativeReals
      3 :     0 :  None :  None : False :  True : NonNegativeReals
      4 :     0 :  None :  None : False :  True : NonNegativeReals
      5 :     0 :  None :  None : False :  True : NonNegativeReals
      6 :     0 :  None :  None : False :  True : NonNegativeReals
      7 :     0 :  None :  None : False :  True : NonNegativeReals
y : Size=10, Index=j
    Key : Lower : Value : Upper : Fixed : Stale : Domain
      0 :     0 :  None :  None : False :  True : NonNegativeReals
      1 :     0 :  None :  None : False :  True : NonNegativeReals
      2 :     0 :  None :  None : False :  True : NonNegativeReals
      3 :     0 :  None :  None : False :  True : NonNegativeReals
      4 :     0 :  None :  None : False :

In [6]:
#print(f"{len(c)=}")
#print(f"{len(model.y)=}")

def objective(model):
    return sum(c[j]*model.y[j] for j in model.j)

model.objective = Objective(rule=objective, sense=minimize)

model.objective.pprint()

objective : Size=1, Index=None, Active=True
    Key  : Active : Sense    : Expression
    None :   True : minimize : 2000*y[0] + 1500*y[1] + 4000*y[2] + 1000*y[3] + 2500*y[4] + 3000*y[5] + 800*y[6] + 700*y[7] + 800*y[8]


In [7]:
##########################
# CRASH TIME CONSTRAINTS #
##########################
def crash_time_constraints(model, j):
    return model.y[j] <= diff_time[j]

model.crash_time = Constraint(model.j, rule=crash_time_constraints)

model.crash_time.pprint()


crash_time : Size=10, Index=j, Active=True
    Key : Lower : Body : Upper : Active
      0 :  -Inf : y[0] :   1.0 :   True
      1 :  -Inf : y[1] :   2.0 :   True
      2 :  -Inf : y[2] :   1.0 :   True
      3 :  -Inf : y[3] :   0.5 :   True
      4 :  -Inf : y[4] :   2.0 :   True
      5 :  -Inf : y[5] :   2.0 :   True
      6 :  -Inf : y[6] :   1.0 :   True
      7 :  -Inf : y[7] :   2.0 :   True
      8 :  -Inf : y[8] :   0.5 :   True
      9 :  -Inf : y[9] :   0.0 :   True


In [8]:
#######################
# NETWORK CONSTRAINTS #
#######################
def network_limit_constraints(model, constraintList):
    constraintList.add(expr = model.x[0] == 0)
    for k, v in res.items():
        constraintList.add(expr = model.x[v[1]] + model.y[k[1]] - model.x[v[0]] >= normal_time[k[1]])
    constraintList.add(expr = model.x[len(model.x)-1] <= 13)
    constraintList.pprint()
    return

In [9]:
model.network_constraints = ConstraintList()
network_limit_constraints(model, model.network_constraints)

network_constraints : Size=12, Index=network_constraints_index, Active=True
    Key : Lower : Body               : Upper : Active
      1 :   0.0 :               x[0] :   0.0 :   True
      2 :   3.0 : x[1] + y[0] - x[0] :  +Inf :   True
      3 :   5.0 : x[2] + y[1] - x[1] :  +Inf :   True
      4 :   3.0 : x[3] + y[2] - x[1] :  +Inf :   True
      5 :   1.0 : x[4] + y[3] - x[3] :  +Inf :   True
      6 :   0.0 : x[4] + y[9] - x[2] :  +Inf :   True
      7 :   4.0 : x[5] + y[5] - x[4] :  +Inf :   True
      8 :   2.0 : x[5] + y[6] - x[3] :  +Inf :   True
      9 :   3.0 : x[6] + y[4] - x[2] :  +Inf :   True
     10 :   3.0 : x[6] + y[7] - x[5] :  +Inf :   True
     11 :   2.0 : x[7] + y[8] - x[6] :  +Inf :   True
     12 :  -Inf :               x[7] :  13.0 :   True


In [10]:
Solver = SolverFactory('gurobi')
Results = Solver.solve(model)

In [11]:
model.x.display()

x : Size=8, Index=i
    Key : Lower : Value : Upper : Fixed : Stale : Domain
      0 :     0 :   0.0 :  None : False : False : NonNegativeReals
      1 :     0 :   2.5 :  None : False : False : NonNegativeReals
      2 :     0 :   6.5 :  None : False : False : NonNegativeReals
      3 :     0 :   5.5 :  None : False : False : NonNegativeReals
      4 :     0 :   6.5 :  None : False : False : NonNegativeReals
      5 :     0 :  10.5 :  None : False : False : NonNegativeReals
      6 :     0 :  11.5 :  None : False : False : NonNegativeReals
      7 :     0 :  13.0 :  None : False : False : NonNegativeReals


In [12]:
model.y.display()

y : Size=10, Index=j
    Key : Lower : Value : Upper : Fixed : Stale : Domain
      0 :     0 :   0.5 :  None : False : False : NonNegativeReals
      1 :     0 :   1.0 :  None : False : False : NonNegativeReals
      2 :     0 :   0.0 :  None : False : False : NonNegativeReals
      3 :     0 :   0.0 :  None : False : False : NonNegativeReals
      4 :     0 :   0.0 :  None : False : False : NonNegativeReals
      5 :     0 :   0.0 :  None : False : False : NonNegativeReals
      6 :     0 :   0.0 :  None : False : False : NonNegativeReals
      7 :     0 :   2.0 :  None : False : False : NonNegativeReals
      8 :     0 :   0.5 :  None : False : False : NonNegativeReals
      9 :     0 :   0.0 :  None : False : False : NonNegativeReals


In [13]:
model.display()

Model unknown

  Variables:
    x : Size=8, Index=i
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          0 :     0 :   0.0 :  None : False : False : NonNegativeReals
          1 :     0 :   2.5 :  None : False : False : NonNegativeReals
          2 :     0 :   6.5 :  None : False : False : NonNegativeReals
          3 :     0 :   5.5 :  None : False : False : NonNegativeReals
          4 :     0 :   6.5 :  None : False : False : NonNegativeReals
          5 :     0 :  10.5 :  None : False : False : NonNegativeReals
          6 :     0 :  11.5 :  None : False : False : NonNegativeReals
          7 :     0 :  13.0 :  None : False : False : NonNegativeReals
    y : Size=10, Index=j
        Key : Lower : Value : Upper : Fixed : Stale : Domain
          0 :     0 :   0.5 :  None : False : False : NonNegativeReals
          1 :     0 :   1.0 :  None : False : False : NonNegativeReals
          2 :     0 :   0.0 :  None : False : False : NonNegativeReals
          3 :     0 